### ISSUE TITLE
Cannot find the rmf_battery package after colcon build

### ISSUE THREAD

**Issue by Ngochuy2137** [open-rmf/rmf_battery#21]
### Required information:
- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - source
- OpenRMF version or commit hash
  - main branch ros2
- ROS distribution and version:
  - galactic
- ROS installation type:
  - source
### Description of the bug

I cannot find the rmf_battery package after colcon build

When I colcon build, everything was ok:
`colcon build --packages-up-to rmf_battery`

> Starting >>> rmf_traffic
> [0.355s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/user/ros2_workspaces/test_ros2_ws/install/demo_pkg' in the environment variable AMENT_PREFIX_PATH doesn't exist
> [0.356s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/user/ros2_workspaces/test_ros2_ws/install/demo_pkg' in the environment variable CMAKE_PREFIX_PATH doesn't exist
> [0.356s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/user/ros2_workspaces/test_ros2_ws/install/rmf_battery' in the environment variable CMAKE_PREFIX_PATH doesn't exist
> [Processing: rmf_traffic]                             
> [Processing: rmf_traffic]                                     
> [Processing: rmf_traffic]                                       
> [Processing: rmf_traffic]                                       
> Finished <<< rmf_traffic [2min 16s]                              
> Starting >>> rmf_battery
> Finished <<< rmf_battery [15.7s]                            
> 
> Summary: 2 packages finished [2min 32s]

But when I look for the package by `ros2 pkg prefix --share rmf_battery`
It outputs:
> Package not found

Is this because of using eigen3_cmake_module instead of ament_cmake ?

**Comment by Yadunund** [comment]
hi @Ngochuy2137 ,

`ros2 pkg prefix --share rmf_battery` does not return any pkg dir as `rmf_battery` is registered as a pure `cmake` package and not `ament_cmake`. This was done to remove any ROS 2 dependency on this package so that users can use this library for their projects without needing ROS 2 installed on their system.

Are you having trouble using `rmf_battery` with your custom package? An example to link `rmf_battery` to another cmake package can be seen [here](https://github.com/open-rmf/rmf_task/blob/a548bacb2b5ede18a7cb5a9e40322a1b808d39be/rmf_task/CMakeLists.txt#L25-L46). Make sure to include `<depend>rmf_battery</depend>` in your package's `package.xml` file.

**Comment by HappySamuel** [comment]
Hi @Ngochuy2137 

You can try to install rmf-battery via debian package.
`$ sudo apt install ros-$ROS_DISTRO-rmf-battery`

Best,
Samuel

**Comment by Yadunund** [comment]
The problem has been addressed in https://github.com/open-rmf/rmf_battery/pull/22. You should now be able to find this package as an ament resource. 

> You can try to install rmf-battery via debian package directly, then you don't have to worry about colcon build yourself.

There may be many reasons why a wants to build a package from source. Installing the binary version should not be the way to address this issue. Especially if it could lead to more issues with colcon overlay/underlay mixing.
